//array de obj

const paises =[
    { pais: "Afeganistão", capital: "Cabul" },
    { pais: "Albânia", capital: "Tirana" },
    { pais: "Argélia", capital: "Argel" },
    { pais: "Andorra", capital: "Andorra-a-Velha" },
    { pais: "Angola", capital: "Luanda" },
    { pais: "Antígua e Barbuda", capital: "Saint John's" },
    { pais: "Argentina", capital: "Buenos Aires" },
    { pais: "Armênia", capital: "Erevan" },
    { pais: "Austrália", capital: "Camberra" },
    { pais: "Áustria", capital: "Viena" },
    { pais: "Azerbaijão", capital: "Baku" },
    { pais: "Bahamas", capital: "Nassau" },
    { pais: "Bahrein", capital: "Manama" },
    { pais: "Bangladesh", capital: "Daca" },
    { pais: "Barbados", capital: "Bridgetown" },
    { pais: "Belarus", capital: "Minsk" },
    { pais: "Bélgica", capital: "Bruxelas" },
    { pais: "Belize", capital: "Belmopan" },
    { pais: "Benim", capital: "Porto Novo" },
    { pais: "Butão", capital: "Timbu" },
    { pais: "Bolívia", capital: "Sucre" },
    { pais: "Bósnia e Herzegovina", capital: "Sarajevo" },
    { pais: "Botsuana", capital: "Gaborone" },
    { pais: "Brasil", capital: "Brasília" },
    { pais: "Brunei", capital: "Bandar Seri Begawan" },
    { pais: "Bulgária", capital: "Sófia" },
    { pais: "Burquina Faso", capital: "Ouagadougou" },
    { pais: "Burundi", capital: "Gitega" },
    { pais: "Cabo Verde", capital: "Praia" },
    { pais: "Camboja", capital: "Phnom Penh" },
    { pais: "Camarões", capital: "Iaundé" },
    { pais: "Canadá", capital: "Ottawa" },
    { pais: "Catar", capital: "Doha" },
    { pais: "Chade", capital: "N'Djamena" },
    { pais: "Chile", capital: "Santiago" },
    { pais: "China", capital: "Pequim" },
    { pais: "Chipre", capital: "Nicósia" },
    { pais: "Colômbia", capital: "Bogotá" },
    { pais: "Comores", capital: "Moroni" },
    { pais: "Coreia do Norte", capital: "Pyongyang" },
    { pais: "Coreia do Sul", capital: "Seul" },
    { pais: "Costa do Marfim", capital: "Yamoussoukro" },
    { pais: "Costa Rica", capital: "São José" },
    { pais: "Croácia", capital: "Zagreb" },
    { pais: "Cuba", capital: "Havana" },
    { pais: "Dinamarca", capital: "Copenhague" },
    { pais: "Djibuti", capital: "Djibuti" },
    { pais: "Dominica", capital: "Roseau" },
    { pais: "Egito", capital: "Cairo" },
    { pais: "El Salvador", capital: "San Salvador" },
    { pais: "Emirados Árabes Unidos", capital: "Abu Dhabi" },
    { pais: "Equador", capital: "Quito" },
    { pais: "Eritreia", capital: "Asmara" },
    { pais: "Eslováquia", capital: "Bratislava" },
    { pais: "Eslovênia", capital: "Liubliana" },
    { pais: "Espanha", capital: "Madri" },
    { pais: "Essuatíni", capital: "Mbabane" },
    { pais: "Estados Unidos", capital: "Washington, D.C." },
    { pais: "Estônia", capital: "Tallinn" },
    { pais: "Etiópia", capital: "Adis Abeba" },
    { pais: "Fiji", capital: "Suva" },
    { pais: "Filipinas", capital: "Manila" },
    { pais: "Finlândia", capital: "Helsinque" },
    { pais: "França", capital: "Paris" },
    { pais: "Gabão", capital: "Libreville" },
    { pais: "Gâmbia", capital: "Banjul" },
    { pais: "Gana", capital: "Acra" },
    { pais: "Geórgia", capital: "Tbilisi" },
    { pais: "Alemanha", capital: "Berlim" },
    { pais: "Granada", capital: "Saint George's" },
    { pais: "Grécia", capital: "Atenas" },
    { pais: "Guatemala", capital: "Cidade da Guatemala" },
    { pais: "Guiana", capital: "Georgetown" },
    { pais: "Guiné", capital: "Conacri" },
    { pais: "Guiné-Bissau", capital: "Bissau" },
    { pais: "Guiné Equatorial", capital: "Malabo" },
    { pais: "Haiti", capital: "Porto Príncipe" },
    { pais: "Honduras", capital: "Tegucigalpa" },
    { pais: "Hungria", capital: "Budapeste" },
    { pais: "Islândia", capital: "Reykjavík" },
    { pais: "Índia", capital: "Nova Deli" },
    { pais: "Indonésia", capital: "Jacarta" },
    { pais: "Irã", capital: "Teerã" },
    { pais: "Iraque", capital: "Bagdá" },
    { pais: "Irlanda", capital: "Dublin" },
    { pais: "Israel", capital: "Jerusalém" },
    { pais: "Itália", capital: "Roma" },
    { pais: "Jamaica", capital: "Kingston" },
    { pais: "Japão", capital: "Tóquio" },
    { pais: "Jordânia", capital: "Amã" },
    { pais: "Cazaquistão", capital: "Astana" },
    { pais: "Quênia", capital: "Nairóbi" },
    { pais: "Quiribati", capital: "Taraua" },
    { pais: "Kuwait", capital: "Cidade do Kuwait" },
    { pais: "Quirguistão", capital: "Bisqueque" },
    { pais: "Laos", capital: "Vientiane" },
    { pais: "Letônia", capital: "Riga" },
    { pais: "Líbano", capital: "Beirute" },
    { pais: "Lesoto", capital: "Maseru" },
    { pais: "Libéria", capital: "Monróvia" },
    { pais: "Líbia", capital: "Trípoli" },
    { pais: "Liechtenstein", capital: "Vaduz" },
    { pais: "Lituânia", capital: "Vilnius" },
    { pais: "Luxemburgo", capital: "Luxemburgo" },
    { pais: "Madagascar", capital: "Antananarivo" },
    { pais: "Malaui", capital: "Lilongue" },
    { pais: "Malásia", capital: "Kuala Lumpur" },
    { pais: "Maldivas", capital: "Malé" },
    { pais: "Mali", capital: "Bamako" },
    { pais: "Malta", capital: "Valeta" },
    { pais: "Ilhas Marshall", capital: "Majuro" },
    { pais: "Mauritânia", capital: "Nouakchott" },
    { pais: "Maurício", capital: "Port Louis" },
    { pais: "México", capital: "Cidade do México" },
    { pais: "Micronésia", capital: "Palikir" },
    { pais: "Moldávia", capital: "Chisinau" },
    { pais: "Mônaco", capital: "Mônaco" },
    { pais: "Mongólia", capital: "Ulan Bator" },
    { pais: "Montenegro", capital: "Podgorica" },
    { pais: "Marrocos", capital: "Rabat" },
    { pais: "Moçambique", capital: "Maputo" },
    { pais: "Mianmar", capital: "Naypyidaw" },
    { pais: "Namíbia", capital: "Windhoek" },
    { pais: "Nauru", capital: "Yaren" },
    { pais: "Nepal", capital: "Catmandu" },
    { pais: "Holanda", capital: "Amsterdã" },
    { pais: "Nova Zelândia", capital: "Wellington" },
    { pais: "Nicarágua", capital: "Manágua" },
    { pais: "Níger", capital: "Niamey" },
    { pais: "Nigéria", capital: "Abuja" },
    { pais: "Macedônia do Norte", capital: "Skopje" },
    { pais: "Noruega", capital: "Oslo" },
    { pais: "Omã", capital: "Mascate" },
    { pais: "Paquistão", capital: "Islamabad" },
    { pais: "Palau", capital: "Ngerulmud" },
    { pais: "Palestina", capital: "Jerusalém Oriental" },
    { pais: "Panamá", capital: "Cidade do Panamá" },
    { pais: "Papua-Nova Guiné", capital: "Port Moresby" },
    { pais: "Paraguai", capital: "Assunção" },
    { pais: "Peru", capital: "Lima" },
    { pais: "Polônia", capital: "Varsóvia" },
    { pais: "Portugal", capital: "Lisboa" },
    { pais: "Reino Unido", capital: "Londres" },
    { pais: "República Centro-Africana", capital: "Bangui" },
    { pais: "República Democrática do Congo", capital: "Kinshasa" },
    { pais: "República do Congo", capital: "Brazzaville" },
    { pais: "República Dominicana", capital: "Santo Domingo" },
    { pais: "República Tcheca", capital: "Praga" },
    { pais: "Romênia", capital: "Bucareste" },
    { pais: "Rússia", capital: "Moscou" },
    { pais: "Ruanda", capital: "Kigali" },
    { pais: "São Cristóvão e Névis", capital: "Basseterre" },
    { pais: "Santa Lúcia", capital: "Castries" },
    { pais: "São Vicente e Granadinas", capital: "Kingstown" },
    { pais: "Samoa", capital: "Apia" },
    { pais: "San Marino", capital: "San Marino" },
    { pais: "São Tomé e Príncipe", capital: "São Tomé" },
    { pais: "Senegal", capital: "Dacar" },
    { pais: "Sérvia", capital: "Belgrado" },
    { pais: "Seicheles", capital: "Vitória" },
    { pais: "Serra Leoa", capital: "Freetown" },
    { pais: "Singapura", capital: "Singapura" },
    { pais: "Síria", capital: "Damasco" },
    { pais: "Somália", capital: "Mogadíscio" },
    { pais: "África do Sul", capital: "Pretória" },
    { pais: "Sudão do Sul", capital: "Juba" },
    { pais: "Espanha", capital: "Madri" },
    { pais: "Sri Lanka", capital: "Sri Jayawardenepura Kotte" },
    { pais: "Sudão", capital: "Cartum" },
    { pais: "Suriname", capital: "Paramaribo" },
    { pais: "Suécia", capital: "Estocolmo" },
    { pais: "Suíça", capital: "Berna" },
    { pais: "Tailândia", capital: "Bangcoc" },
    { pais: "Tajiquistão", capital: "Dushanbe" },
    { pais: "Tanzânia", capital: "Dodoma" },
    { pais: "Timor-Leste", capital: "Dili" },
    { pais: "Togo", capital: "Lomé" },
    { pais: "Tonga", capital: "Nuku'alofa" },
    { pais: "Trinidad e Tobago", capital: "Port of Spain" },
    { pais: "Tunísia", capital: "Túnis" },
    { pais: "Turquia", capital: "Ancara" },
    { pais: "Turcomenistão", capital: "Asgabate" },
    { pais: "Tuvalu", capital: "Funafuti" },
    { pais: "Uganda", capital: "Campala" },
    { pais: "Ucrânia", capital: "Kiev" },
    { pais: "Uruguai", capital: "Montevidéu" },
    { pais: "Uzbequistão", capital: "Tashkent" },
    { pais: "Vanuatu", capital: "Port Vila" },
    { pais: "Vaticano", capital: "Cidade do Vaticano" },
    { pais: "Venezuela", capital: "Caracas" },
    { pais: "Vietnã", capital: "Hanói" },
    { pais: "Iêmen", capital: "Sana" },
    { pais: "Zâmbia", capital: "Lusaca" },
    { pais: "Zimbábue", capital: "Harare" }
];

export const gerarPergunta = () => {
    const index = Math.floor(Math.random() * paises.length);
    return paises[index];
};

export const verificarResposta = (pais, resposta) => {
    const encontrado = paises.find(p => p.pais === pais);
    if(!encontrado) return false;
    return encontrado.capital.toLowerCase() === resposta.toLowerCase();
};